server:
  port: 8095

spring:
  datasource:
    platform: postgres
    url: jdbc:postgres://ikmrcnplwasrbo:c8c0aa166962f81ae46d73500003ea13630ebbdb22b40739385f76559fab6c12@ec2-3-214-4-151.compute-1.amazonaws.com:5432/d1d1f596cpdmuf
    username: ikmrcnplwasrbo
    password: c8c0aa166962f81ae46d73500003ea13630ebbdb22b40739385f76559fab6c12
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

service:
  books: 'https://s3-ap-southeast-1.amazonaws.com/he-public-data/books8f8fe52.json'
  images: 'https://s3-ap-southeast-1.amazonaws.com/he-public-data/bookimage816b123.json'
  payment: 'https://test.instamojo.com/api/1.1/payment-requests/'

payment:
  credentials:
    key: 'test_ae839097ff683c6075a2f62a35a'
    token: 'test_756c98688fc5e85bd6e8237de2d'